[versions]
agp = "8.5.2"
android-compileSdk = "34"
android-minSdk = "21"
android-targetSdk = "34"
androidx-activityCompose = "1.9.0"
androidx-lifecycle = "2.8.4"
compose-multiplatform = "1.7.0"
junit = "4.13.2"
kotlin = "2.1.0"
kotlin-android = "1.8.0"
kapt = "1.8.0"
koin = "4.0.2"
room-database = "2.6.1"
signalr = "7.0.0"
retrofit = "2.9.0"
okhttp3 = "3.12.1"
nanohttpd = "2.3.1"
kotlinx-serialization-json = "1.8.0"

[libraries]
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
#koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
#koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
#koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room-database"}
room-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "room-database"}
room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "room-database"}
signalr = { group = "com.microsoft.signalr", name = "signalr", version.ref = "signalr"}
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3"}
nanohttpd = { group = "org.nanohttpd", name = "nanohttpd", version.ref = "nanohttpd"}
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }